name: build

on:
  push:
    branches:
      - main
      - 'dev.*'
  pull_request:
  merge_group:

jobs:
  build:
    name: Build on Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # supported node versions
        node: [18]
        os: ['ubuntu-latest']
        include:
          # additional test for current node version on windows
          - node: 18
            os: windows-latest
    steps:
      - run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i -g npm
      - run: |
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
      - run: npm ci
      - run: npm run depcheck && npm run depcheck --workspaces
      - run: npm run lint:ci
      - run: npm run format:ci
      - run: npm run build --workspaces
      - run: npm run test --workspaces
      # Delete product-stack-snapshots which is created by test.
      # Without this step, synth fails.
      - run: npm run clean:product --workspace usecases/blea-gov-base-ct
      - run: npm run synth --workspaces
