name: build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # supported node versions
        node: [14, 16]
        os: ['ubuntu-latest']
        include:
          # additional test for current node version on windows
          - node: 16
            os: windows-latest
    steps:
      - run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i -g npm
      - run: |
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
      - run: npm ci
      - run: npm run lint:ci
      - run: npm run format:ci
      - run: npm run build --workspaces
      - run: npm run test --workspaces
      - run: npm run synth:dev --workspaces
